import React from 'react';
import Footer from '../../footer/Footer';
import styles from './BackofficeLayout.module.scss';
import Head from 'next/head';
import Sidebar from '../../dashboard/Sidebar/Sidebar';

const BackofficeLayout = ({children}) => {
    return (
        <>
            <Head>
                <title>Netflix</title>
                <meta name="description" content="Generated by netflix" />
                <link rel="icon" href="/netflix.ico" />
            </Head>
            <main className={styles.main}>
                <Sidebar/>
                <div className={styles.body}>
                    {children}
                </div>
            </main>
            <footer>
                <Footer />
            </footer>
        </>
    );
};

export default BackofficeLayout;