import React from 'react';
import HeaderLogo from '../../header/HeaderLogo/HeaderLogo';
import HeaderMenu from '../../header/HeaderMenu/HeaderMenu';
import SubHeader from '../../header/SubHeader/SubHeader';
import Footer from '../../footer/Footer';
// import '../../styles/styles.scss';
import styles from './MainLayout.module.scss';
import Head from 'next/head'

const MainLayout = ({children}) => {
    return (
        <>
            <Head>
                <title>Netflix</title>
                <meta name="description" content="Generated by netflix" />
                <link rel="icon" href="/netflix.ico" />
            </Head>
            <header className={styles.header__main}>
                <HeaderLogo />
                <HeaderMenu />
                <SubHeader />
            </header>
            <main className={styles.main}>
                {children}
            </main>
            <footer>
                <Footer />
            </footer>
        </>
    );
};

export default MainLayout;