import React from 'react';
import HeaderLogo from '../../header/HeaderLogo/HeaderLogo';
import Footer from '../../footer/Footer';
import styles from './RegisterLayout.module.scss';
import LogoImg from '../../../assets/images/Netflix-logo.png';
import Head from 'next/head';
import Input from '../../UI/Input/Input';
import Link from 'next/link';


const RegisterLayout = ({children}) => {
    return (
        <>
            <Head>
                <title>Netflix</title>
                <meta name="description" content="Generated by netflix" />
                <link rel="icon" href="/netflix.ico" />
            </Head>
            <main className={styles.main}>
                <div className={styles.body}>
                    <div className={styles.netflix__header}>
                        <Link href="/">
                            <a>
                                <img src={LogoImg.src} alt="Netflix" />
                            </a>
                        </Link>
                        <Link href="/login">
                            <a className={styles.link}>{"S'identifier"}</a>
                        </Link>
                    </div>
                    <div className='content'>
                        {children}
                    </div>
                </div>
            </main>
            <footer>
                <Footer />
            </footer>
        </>
    );
};

export default RegisterLayout;